### ISSUE TITLE
Add 7s scores

### ISSUE THREAD

**Issue by matttrenary** [matttrenary/rugby-ratings#11]
### 7s
- ~~iowa state winning ncr qualifier 7s in oklahoma april 22~~
- ~~iowa state winning heart of america 7s in march/april 22~~
- ~~Missing games from SCRC 7s warmup 2/26/2022 won by Auburn.~~
- ~~Missing games from Southern Conference 7s 2/26/2022 at Wilmington~~
- ~~Missing games from Midnight 7s at St. Bonaventure 4/2/2022~~
- ~~Missing games from Mooseman 7s 3/19/2022~~
- ~~Missing games from Furman 7s 2/12/2022~~
- ~~Missing games from Pitt Dome 7s 2/19/2022 - Pitt played split teams~~
- ~~https://www.goffrugbyreport.com/news/cal-edges-ucla-pac-7s-title~~
- ~~https://www.goffrugbyreport.com/news/cal-ucla-3-0-day-one-pac-7s~~
- ~~https://www.goffrugbyreport.com/news/both-cal-teams-unbeaten-west-coast-7s (probably scores on west coast 7s FB)~~

### 15s
- Don't think we should add since they are shortened games. https://www.goffrugbyreport.com/news/successful-hitout-many-cal-wins-storer-classic

**Comment by grjanke** [comment]
Yeah, we should stick to full-length, first side games.

I think I'd be against adding Pitt's games for 2022 Pitt Dome 7s. Games with split teams (and no designated first side) can't count as first side games.

**Comment by grjanke** [comment]
I'm striking through items on your list once they are completely finished.

**Comment by grjanke** [comment]
- [List of teams in 2/26 Dixie Cup 7s (SCRC Warmup); no scores anywhere](https://www.youtube.com/watch?v=F8Dhfw7_ks8)
- List of Teams in 2/19 Pitt Dome 7s (no scores anywhere other than Wheeling): Pitt Grey, Wheeling, Dayton, West Chester, Pitt Blue, Franciscan, IUP, Cincinnati

**Comment by grjanke** [comment]
- April 22 S Nazarene CRC Qualifier: Completely logged
- 2022 Heart of America 7s: All games logged, but some scores missing
- Midnight 7s at St. Bonaventure: All first side games logged
- Mooseman 7s: All Division 1 matchups should be found, some scores missing (a lot of conflicting info regarding this tournament; I think I got it right)
- Furman 7s: All matchups found, some scores missing

**Comment by grjanke** [comment]
- 2021 West Coast 7s: All games logged, but some scores missing
- 2021 PAC 7s: Completely logged

**Comment by grjanke** [comment]
I'm done with almost everything in this issue.

### 7s Tournaments Still Missing Matchups
(Other tournaments are missing scores, but all games appear in the table)
- 2022 Heart of America North Seeding Tournament
- 2022 Heart of America South Seeding Tournament
- 2022 SCRC Warmup / Dixie Cup 7s on 2/26
- 2022 Pitt Dome 7s aka Bridge City 7s on 2/19

I think we are only getting these matchups if we ask tournament organizers. I spent hours looking.

**In the meantime, we should move on to bigger and better things.**

**Comment by matttrenary** [comment]
Not a priority and may not be possible.
