### ISSUE TITLE
List Rankings

### ISSUE THREAD

**Issue by grjanke** [matttrenary/rugby-ratings#12]
**We should list each team's ranking (based on its ELO rating).**

The general public will appreciate having a number to the left of each team's name. While the ELO ratings are important and useful, fans care the most about where their team **ranks** compared to other teams. Otherwise they need to count down the list in order to figure this out.

**Comment by matttrenary** [comment]
Agreed. I think the terminology we'll end up with, and what will be displayed in the menu is: Results, Ratings, and Rankings. Ratings will be Elo but with a ranking number, Rankings will be pairwise.

**Comment by grjanke** [comment]
Is there a good reason not to display ELO and PWR on the same page? The table has a lot of room to fit more information.

**Comment by matttrenary** [comment]
Yeah that makes sense and I guess we can switch to the Ranking terminology for both since that's probably better understood publicly.

**Comment by grjanke** [comment]
PWR and ELO are now on the same page. I'm changing the header to "Rankings" instead of "Ratings", and then this is done!
