### ISSUE TITLE
Date Calc Different Depending on OS

### ISSUE THREAD

**Issue by grjanke** [matttrenary/rugby-ratings#30]
Windows and Mac require a different wildcard in the date string to make the date show up correctly on the website. Solve this!

**Comment by grjanke** [comment]
I just opened a new branch (resolve-os-diffs) and pushed three commits.

What was the issue?
In python's datetime library, the strftime() func originates from C, and the C is compiled with a different version depending on a computer's operating system. The date formats (which begin with %) are different for each OS.
- For MacOS formats, I ran "man strftime" in the shell
- For Windows formats, see [here](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/strftime-wcsftime-strftime-l-wcsftime-l?view=msvc-170&redirectedfrom=MSDN)
- For Linux formats, see [here](https://www.man7.org/linux/man-pages/man3/strftime.3.html)

How did I fix the issue?
Before our implementation of strftime() in site_builder.py and calc_ratings.py, I added an if-then statement that checks which operating system the user is using (see lines 46 and 318, respectively). After that, it uses the operating-system-specific function call.

**Comment by grjanke** [comment]
@matttrenary Please test my changes on your Windows system, using the commands below.
`
git pull
git checkout resolve-os-diffs
python calc_ratings.py
python site_builder.py
python -m http.server
`
Then, navigate to (probably?) localhost:8000 and scroll through the site and make sure all of the dates look normal.

If we're all good, then I can merge the branches! Otherwise, I must have messed up the date formats on Windows.

**Comment by matttrenary** [comment]
It worked!

Not sure if related, but the datestamp at the bottom of a page is a little funky:
![image](https://github.com/user-attachments/assets/43411605-78f0-41c5-8f80-8431fba82235)

**Comment by matttrenary** [comment]
Updated code and committed. Can you test?

The "#" character works on Windows like the "-" character on Mac in date formatting. I was also getting full time zone names instead of acronyms so I decided to use a couple more packages in order to use %Z in the date format for the time zone. I'd expect that you could do the same and simplify the Mac code, removing the if/else for daylight savings.

**Comment by grjanke** [comment]
Oops. Didn't get around to updating the Mac code if/else for daylight savings, but that's beyond the scope of this issue, since the goal was just to get it working on all OSes. Can fix later as part of code cleanup.

Copyright symbol and everything else works. Merged the branch. Closing this issue!
