### ISSUE TITLE
Move to timestamp toward top of rankings page

### ISSUE THREAD

**Issue by matttrenary** [matttrenary/rugby-ratings#32]
Move the timestamp currently at the bottom of the rankings page to the top of the page so that users see that the site is frequently maintained. Maybe put it under the title. Maybe make it more specific like "Rankings updated [blah]" or "Game scores updated through [blah]".

**Comment by grjanke** [comment]
@ray060708 Re-opening this issue since we've gotta fix the Jinja template files, not the html files themselves (since Jinja templates overwrite html files whenever we run site_builder.py).

**Comment by grjanke** [comment]
Nice job @ray060708 !
