### ISSUE TITLE
Rankings page initially displaying both 15s and 7s tables

### ISSUE THREAD

**Issue by matttrenary** [matttrenary/rugby-ratings#33]
Both divs have the active class and are showing. 15s above, 7s below. I'm assuming this isn't desired behavior, and only 15s should be active and showing.

**Comment by matttrenary** [comment]
Looks like both the 15s and 7s blocks within main within rebuild.py are setting active to 'show active'. I think we should only do this for 15s.

Also, I'm thinking we just remove the argparse for 15s and 7s and clean up main a bit. I don't think we have been using the 15s/7s split much. @grjanke can you add your two cents on removing that?

**Comment by grjanke** [comment]
I agree; I'm in favor of removing the 15s vs 7s argparse. I've never used it.

**Comment by matttrenary** [comment]
Removed 'show active' for 7s. 15s is the default.
Argparse removed via #37
