### ISSUE TITLE
Add 7s/15s toggle on frontpage

### ISSUE THREAD

**Issue by matttrenary** [matttrenary/rugby-ratings#36]

**Comment by grjanke** [comment]
See the new branch (index-separate-7s-15s).

I separated the two, but right now I've kept them on one tab. The reasoning is that if there are 7s games but no 15s games, visitors will just see "No 15s games this week" and won't take the effort to click the 7s tab. Keeping them on one tab peaks visitor interest better.

Thoughts @matttrenary ? I note that I do think separating them into tabs does look slightly cleaner.

**Comment by matttrenary** [comment]
Looks good enough for me!

I do think the score submission form should move away from the frontpage though. Seems out of place at this point. Doesn't need to be tied to this issue though.

**Comment by grjanke** [comment]
Merge completed! It's functional now, and we can play around with style as we see fit.

Created Issue #39 for the score submission form.
