### ISSUE TITLE
Pick domain

### ISSUE THREAD

**Issue by matttrenary** [matttrenary/rugby-ratings#4]
And don't forget to update the links to remove /rugby-ratings

**Comment by matttrenary** [comment]
vantagerugby.com
scorerugby.com
rugbytracker.com
recordrugby.com

**Comment by grjanke** [comment]
Other ideas:

rugbyhawk.com
rugbyranks.com
rugbycomps.com
rugbycompass.com

**Comment by grjanke** [comment]
Coach says he likes rugbyhawk.com or something similar.

**Comment by matttrenary** [comment]
rugbyhawk decided and implemented
